@echo off
_TOOLS\bincompiler GAME.TXT GAME.CAT
_TOOLS\bincompiler SONIC1\STAGES.TXT SONIC1\STAGES.BIN
_TOOLS\bincompiler SONIC1\STAGE\GREENHILL\PROPERTIES.TXT SONIC1\STAGE\GREENHILL\PROPERTIES.BIN
_TOOLS\bincompiler SONIC2\STAGES.TXT SONIC2\STAGES.BIN
_TOOLS\bincompiler SONIC3K\STAGES.TXT SONIC3K\STAGES.BIN
_TOOLS\bincompiler SONICCD\STAGES.TXT SONICCD\STAGES.BIN
MEGAMAN2\BUILD.BAT